### ISSUE TITLE
Incorrect socks5 client max request size in the handshaking

### ISSUE THREAD

**Issue by schemacs** [eahydra/socks#2]
According to [RFC 1928 ](http://www.faqs.org/rfcs/rfc1928.html), the max request size should be 262 bytes: 1(ver) + 1(rep) + 1(rsv) + 1(atype) + 1(domain length) + 255(domain, 2^8) + 2(port)

```
   +----+-----+-------+------+----------+----------+
    |VER | REP |  RSV  | ATYP | BND.ADDR | BND.PORT |
    +----+-----+-------+------+----------+----------+
    | 1  |  1  | X'00' |  1   | Variable |    2     |
    +----+-----+-------+------+----------+----------+
```

https://github.com/eahydra/socks/blob/master/socks5_client.go#L222, so here 263 is not correct.

**Comment by eahydra** [comment]
More than one byte will not cause any problems.  But I will also fix it.
