### ISSUE TITLE
socksd的配置文件

### ISSUE THREAD

**Issue by bizky** [eahydra/socks#3]
请问socks.config中第一行的address可以不填端口号吗？以及PAC与proxies中的配置是不是很多可以重复？

**Comment by eahydra** [comment]
address必须填端口。
PAC的配置只能是一个
proxies内的配置可以有多条

**Comment by bizky** [comment]
那么如果我只想做一个本地的socks5代理，是不是可以不用填写upstream了？
这么写
{
    "pac":{
               "address":"127.0.0.1:6666",
        "socks5": "127.0.0.1:6666",
    },
    "proxies":[
        {
            "socks5": ":6666",
        }
    ]
}
可以吗？

**Comment by eahydra** [comment]
可以的。UPSTREAM的作用就是声明另外一台代理服务器的配置信息
